name: Check Disk Space

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-disk-space:
    runs-on: ubuntu-latest
    steps:
      - name: df -h (before free disk)
        run: df -h
      
      - name: free disk space
        uses: jlumbroso/free-disk-space@main
      
      - name: df -h(after free disk)
        run: df -h